def libraryVersion = env.CHANGE_BRANCH ?: env.BRANCH_NAME ?: 'master'

library identifier: "stacc-pipelines@${libraryVersion}", retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'git@github.com:adam-stegienko/stacc.git',
    credentialsId: 'jenkins_github_np'
])

staccServicePipeline(
    moduleDir: 'stacc-google-api-rest',
    appName: 'stacc-google-api-rest',
    sonarProjectName: 'stacc_google_api_rest',
    sonarProjectKey: 'stacc_google_api_rest'
)