@Library('stacc-pipelines') _

staccServicePipeline(
    moduleDir: 'stacc-google-api-rest',
    appName: 'stacc-google-api-rest',
    sonarProjectName: 'stacc_google_api_rest',
    sonarProjectKey: 'stacc_google_api_rest'
)