gateway:
  routes:
    campaign-controller-api: http://campaign-controller-api.dev.svc.cluster.local:8081
    google-api: http://google-ads-api.dev.svc.cluster.local:8082

# OpenAPI properties
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG

app:
  cors:
    mapping: ${APP_CORS_MAPPING:/gw/**}
    allowed-origins: "${APP_CORS_ALLOWED_ORIGINS:https://campaign-controller-dev.apps.stegienko.local}"
    allowed-methods: "${APP_CORS_ALLOWED_METHODS:*}"
    allowed-headers: "${APP_CORS_ALLOWED_HEADERS:*}"
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
