gateway:
  routes:
    campaign-controller-api: http://campaign-controller-api.stage.svc.cluster.local:8081
    google-api: http://google-ads-api.stage.svc.cluster.local:8082

# OpenAPI properties
springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    io.micrometer.tracing: WARN
    org.springframework.web: WARN

app:
  cors:
    mapping: ${APP_CORS_MAPPING:/gw/**}
    allowed-origins: "${APP_CORS_ALLOWED_ORIGINS:https://campaign-controller-stage.apps.stegienko.local}"
    allowed-methods: "${APP_CORS_ALLOWED_METHODS:*}"
    allowed-headers: "${APP_CORS_ALLOWED_HEADERS:*}"
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
