def libraryVersion = env.CHANGE_BRANCH ?: env.BRANCH_NAME ?: 'master'

library identifier: "stacc-pipelines@${libraryVersion}", retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'git@github.com:adam-stegienko/stacc.git',
    credentialsId: 'jenkins_github_np'
])

frontendPipeline(
    moduleDir: 'stacc-ui',
    appName: 'stacc-ui',
    sonarProjectName: 'stacc_ui',
    sonarProjectKey: 'stacc_ui'
)
