@Library('stacc-pipelines') _

staccServicePipeline(
    moduleDir: 'stacc-api-gateway',
    appName: 'stacc-api-gateway',
    sonarProjectName: 'stacc_api_gateway',
    sonarProjectKey: 'stacc_api_gateway'
)