@Library('stacc-pipelines') _

staccServicePipeline(
    moduleDir: 'stacc-scheduler',
    appName: 'stacc-scheduler',
    sonarProjectName: 'stacc_scheduler',
    sonarProjectKey: 'stacc_scheduler'
)